/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 experience.glb -k 
*/
import * as THREE from 'three';
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Float } from '@react-three/drei'

export function Plane(props) {
    const { section } = props;
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/experience.glb')
    const { actions, names } = useAnimations(animations, group)
    return (
        <>
            {/* mundo */}
            {section === 0 ? null :
                <>
                    <group name="Scene">
                        <group name="skills" position={[-13.761, 17.813, -2.501]} rotation={[Math.PI / 2, 0, 2.625]} scale={0.379}>
                            <mesh name="Camera" geometry={nodes.Camera.geometry} material={materials['Material.042']} />
                            <mesh name="Camera_1" geometry={nodes.Camera_1.geometry} material={materials['Material.043']} />
                            <mesh name="Camera_2" geometry={nodes.Camera_2.geometry} material={materials['Material.044']} />
                            <mesh name="Camera_3" geometry={nodes.Camera_3.geometry} material={materials['Material.045']} />
                            <mesh name="Camera_4" geometry={nodes.Camera_4.geometry} material={materials['Material.046']} />
                            <mesh name="Camera_5" geometry={nodes.Camera_5.geometry} material={materials.wood} />
                            <mesh name="Camera_6" geometry={nodes.Camera_6.geometry} material={materials['mat21.002']} />
                            <mesh name="Camera_7" geometry={nodes.Camera_7.geometry} material={materials.mat20} />
                            <mesh name="Camera_8" geometry={nodes.Camera_8.geometry} material={materials.mat9} />
                            <mesh name="Camera_9" geometry={nodes.Camera_9.geometry} material={materials['wood.001']} />
                            <mesh name="Camera_10" geometry={nodes.Camera_10.geometry} material={materials.BeanBag} />
                            <mesh name="Camera_11" geometry={nodes.Camera_11.geometry} material={materials['mat23.002']} />
                            <mesh name="Camera_12" geometry={nodes.Camera_12.geometry} material={materials.mat3} />
                            <mesh name="Camera_13" geometry={nodes.Camera_13.geometry} material={materials['mat16.002']} />
                            <mesh name="Camera_14" geometry={nodes.Camera_14.geometry} material={materials['mat23.003']} />
                            <mesh name="Camera_15" geometry={nodes.Camera_15.geometry} material={materials['mat15.001']} />
                            <mesh name="Camera_16" geometry={nodes.Camera_16.geometry} material={materials['mat17.001']} />
                            <mesh name="Camera_17" geometry={nodes.Camera_17.geometry} material={materials.mat24} />
                            <mesh name="Camera_18" geometry={nodes.Camera_18.geometry} material={materials['mat25.001']} />
                            <mesh name="Camera_19" geometry={nodes.Camera_19.geometry} material={materials['mat5.001']} />
                            <mesh name="Camera_20" geometry={nodes.Camera_20.geometry} material={materials['mat16.003']} />
                            <mesh name="Camera_21" geometry={nodes.Camera_21.geometry} material={materials.mat8} />
                            <mesh name="Camera_22" geometry={nodes.Camera_22.geometry} material={materials.mat16} />
                            <mesh name="Camera_23" geometry={nodes.Camera_23.geometry} material={materials['mat23.001']} />
                            <mesh name="Camera_24" geometry={nodes.Camera_24.geometry} material={materials.mat17} />
                            <mesh name="Camera_25" geometry={nodes.Camera_25.geometry} material={materials.mat15} />
                            <mesh name="Camera_26" geometry={nodes.Camera_26.geometry} material={materials['Material.010']} />
                            <mesh name="Camera_27" geometry={nodes.Camera_27.geometry} material={materials['Material.009']} />
                            <mesh name="Camera_28" geometry={nodes.Camera_28.geometry} material={materials['mat16.001']} />
                            <mesh name="Camera_29" geometry={nodes.Camera_29.geometry} material={materials['mat21.001']} />
                            <mesh name="Camera_30" geometry={nodes.Camera_30.geometry} material={materials.mat1} />
                            <mesh name="Camera_31" geometry={nodes.Camera_31.geometry} material={materials.mat5} />
                            <mesh name="Camera_32" geometry={nodes.Camera_32.geometry} material={materials.mat7} />
                            <mesh name="Camera_33" geometry={nodes.Camera_33.geometry} material={materials.mat10} />
                            <mesh name="Camera_34" geometry={nodes.Camera_34.geometry} material={materials['Material.013']} />
                            <mesh name="Camera_35" geometry={nodes.Camera_35.geometry} material={materials.Metal1DeskLamp1} />
                            <mesh name="Camera_36" geometry={nodes.Camera_36.geometry} material={materials.rubiks_cube_albedo} />
                            <mesh name="Camera_37" geometry={nodes.Camera_37.geometry} material={materials.GrayTone1} />
                            <mesh name="Camera_38" geometry={nodes.Camera_38.geometry} material={materials.GrayTone3} />
                            <mesh name="Camera_39" geometry={nodes.Camera_39.geometry} material={materials.GrayTone2} />
                            <mesh name="Camera_40" geometry={nodes.Camera_40.geometry} material={materials.Top} />
                            <mesh name="Camera_41" geometry={nodes.Camera_41.geometry} material={materials.Supports} />
                            <mesh name="Camera_42" geometry={nodes.Camera_42.geometry} material={materials.mat25} />
                        </group>
                        <group name="tierra" position={[-23.131, 3.692, 36.846]} rotation={[2.521, -0.56, 0.286]} scale={6.702}>
                            <mesh name="group909134206002" geometry={nodes.group909134206002.geometry} material={materials['mat5.002']} />
                            <mesh name="group909134206002_1" geometry={nodes.group909134206002_1.geometry} material={materials['Material.019']} />
                            <mesh name="group909134206002_2" geometry={nodes.group909134206002_2.geometry} material={materials['mat16.004']} />
                            <mesh name="group909134206002_3" geometry={nodes.group909134206002_3.geometry} material={materials['mat17.002']} />
                            <mesh name="group909134206002_4" geometry={nodes.group909134206002_4.geometry} material={materials['Material.017']} />
                            <mesh name="group909134206002_5" geometry={nodes.group909134206002_5.geometry} material={materials['Material.020']} />
                            <mesh name="group909134206002_6" geometry={nodes.group909134206002_6.geometry} material={materials['Material.018']} />
                            <mesh name="group909134206002_7" geometry={nodes.group909134206002_7.geometry} material={materials['Atlas.001']} />
                            <mesh name="group909134206002_8" geometry={nodes.group909134206002_8.geometry} material={materials['Material.031']} />
                            <mesh name="group909134206002_9" geometry={nodes.group909134206002_9.geometry} material={materials['Material.032']} />
                            <mesh name="group909134206002_10" geometry={nodes.group909134206002_10.geometry} material={materials['Material.033']} />
                            <mesh name="group909134206002_11" geometry={nodes.group909134206002_11.geometry} material={materials['Material.034']} />
                            <mesh name="group909134206002_12" geometry={nodes.group909134206002_12.geometry} material={materials['Material.035']} />
                            <mesh name="group909134206002_13" geometry={nodes.group909134206002_13.geometry} material={nodes.group909134206002_13.material} />
                            <mesh name="group909134206002_14" geometry={nodes.group909134206002_14.geometry} material={materials['Material.028']} />
                            <mesh name="group909134206002_15" geometry={nodes.group909134206002_15.geometry} material={materials['Atlas.003']} />
                            <mesh name="group909134206002_16" geometry={nodes.group909134206002_16.geometry} material={materials['Material.029']} />
                            <mesh name="group909134206002_17" geometry={nodes.group909134206002_17.geometry} material={materials['Material.030']} />
                            <mesh name="group909134206002_18" geometry={nodes.group909134206002_18.geometry} material={materials['Material.040']} />
                            <mesh name="group909134206002_19" geometry={nodes.group909134206002_19.geometry} material={materials['Atlas.004']} />
                            <mesh name="group909134206002_20" geometry={nodes.group909134206002_20.geometry} material={materials.principal} />
                            <mesh name="group909134206002_21" geometry={nodes.group909134206002_21.geometry} material={materials['Material.025']} />
                            <mesh name="group909134206002_22" geometry={nodes.group909134206002_22.geometry} material={materials['Material.026']} />
                            <mesh name="group909134206002_23" geometry={nodes.group909134206002_23.geometry} material={materials['Material.027']} />
                            <mesh name="group909134206002_24" geometry={nodes.group909134206002_24.geometry} material={materials['Material.036']} />
                            <mesh name="group909134206002_25" geometry={nodes.group909134206002_25.geometry} material={materials['mat8.001']} />
                            <mesh name="group909134206002_26" geometry={nodes.group909134206002_26.geometry} material={materials['mat15.002']} />
                            <mesh name="group909134206002_27" geometry={nodes.group909134206002_27.geometry} material={materials['mat5.003']} />
                            <mesh name="group909134206002_28" geometry={nodes.group909134206002_28.geometry} material={materials['mat23.005']} />
                            <mesh name="group909134206002_29" geometry={nodes.group909134206002_29.geometry} material={materials.mat13} />
                            <mesh name="group909134206002_30" geometry={nodes.group909134206002_30.geometry} material={materials['mat22.002']} />
                            <mesh name="group909134206002_31" geometry={nodes.group909134206002_31.geometry} material={materials.mat19} />
                            <mesh name="group909134206002_32" geometry={nodes.group909134206002_32.geometry} material={materials.mat14} />
                            <mesh name="group909134206002_33" geometry={nodes.group909134206002_33.geometry} material={materials['Material.037']} />
                            <mesh name="group909134206002_34" geometry={nodes.group909134206002_34.geometry} material={materials['mat21.005']} />
                            <mesh name="group909134206002_35" geometry={nodes.group909134206002_35.geometry} material={materials.spacebits_texture} />
                            <mesh name="group909134206002_36" geometry={nodes.group909134206002_36.geometry} material={materials['Material.038']} />
                            <mesh name="group909134206002_37" geometry={nodes.group909134206002_37.geometry} material={materials['Material.039']} />
                            <mesh name="group909134206002_38" geometry={nodes.group909134206002_38.geometry} material={materials['Material.041']} />
                            <mesh name="group909134206002_39" geometry={nodes.group909134206002_39.geometry} material={materials['Material.057']} />
                        </group>

                        <group name="formas_formation" position={[22.912, 2.073, 28.029]} scale={0.572}>
                            <mesh name="Sphere009" geometry={nodes.Sphere009.geometry} material={materials['paredes formation']} />
                            <mesh name="Sphere009_1" geometry={nodes.Sphere009_1.geometry} material={materials['formation ']} />
                            <mesh name="Sphere009_2" geometry={nodes.Sphere009_2.geometry} material={materials['Material.048']} />
                            <mesh name="Sphere009_3" geometry={nodes.Sphere009_3.geometry} material={materials['Material.049']} />
                        </group>

                        <group name="cilindros_redes_sociales" position={[9.717, 5.248, -12.053]} scale={3.188}>
                            <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.015']} />
                            <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['Material.006']} />
                            <mesh name="Cylinder001_2" geometry={nodes.Cylinder001_2.geometry} material={materials['Material.007']} />
                            <mesh name="Cylinder001_3" geometry={nodes.Cylinder001_3.geometry} material={materials['Material.003']} />
                            <mesh name="Cylinder001_4" geometry={nodes.Cylinder001_4.geometry} material={materials['Material.005']} />
                            <mesh name="Cylinder001_5" geometry={nodes.Cylinder001_5.geometry} material={materials['Material.008']} />
                            <mesh name="Cylinder001_6" geometry={nodes.Cylinder001_6.geometry} material={materials['Material.004']} />
                            <mesh name="Cylinder001_7" geometry={nodes.Cylinder001_7.geometry} material={materials['Material.011']} />
                            <mesh name="Cylinder001_8" geometry={nodes.Cylinder001_8.geometry} material={materials['Material.012']} />
                            <mesh name="Cylinder001_9" geometry={nodes.Cylinder001_9.geometry} material={materials['paredes formation']} />
                            <mesh name="Cylinder001_10" geometry={nodes.Cylinder001_10.geometry} material={materials['Material.054']} />
                            <mesh name="Cylinder001_11" geometry={nodes.Cylinder001_11.geometry} material={materials['Material.014']} />
                            <mesh name="Cylinder001_12" geometry={nodes.Cylinder001_12.geometry} material={materials['mat15.001']} />
                            <mesh name="Cylinder001_13" geometry={nodes.Cylinder001_13.geometry} material={materials['Material.055']} />
                            <mesh name="Cylinder001_14" geometry={nodes.Cylinder001_14.geometry} material={materials['Material.056']} />
                            <mesh name="Cylinder001_15" geometry={nodes.Cylinder001_15.geometry} material={materials['SVGMat.007']} />
                            <mesh name="Cylinder001_16" geometry={nodes.Cylinder001_16.geometry} material={materials['SVGMat.006']} />
                            <mesh name="Cylinder001_17" geometry={nodes.Cylinder001_17.geometry} material={materials['SVGMat.004']} />
                            <mesh name="Cylinder001_18" geometry={nodes.Cylinder001_18.geometry} material={materials['SVGMat.005']} />
                            <mesh name="Cylinder001_19" geometry={nodes.Cylinder001_19.geometry} material={materials.SVGMat} />
                            <mesh name="Cylinder001_20" geometry={nodes.Cylinder001_20.geometry} material={materials['SVGMat.008']} />
                            <mesh name="Cylinder001_21" geometry={nodes.Cylinder001_21.geometry} material={materials['Material.001']} />
                            <mesh name="Cylinder001_22" geometry={nodes.Cylinder001_22.geometry} material={materials['Material.002']} />
                        </group>

                        <group name="paredes" position={[-7.258, 6.76, 26.252]} scale={[4.059, 3.048, 3.048]}>
                            <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['paredes skill']} />
                            <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials['piso skill']} />
                            <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials['paredes proyectos']} />
                            <mesh name="Plane004_3" geometry={nodes.Plane004_3.geometry} material={materials['paredes formation']} />
                            <mesh name="Plane004_4" geometry={nodes.Plane004_4.geometry} material={materials.bordes} />
                            <mesh name="Plane004_5" geometry={nodes.Plane004_5.geometry} material={materials['Material.050']} />
                        </group>
                    </group>

                </>}
        </>
    )
}


useGLTF.preload('/experience.glb')